In [14]:
import pandas as pd
import numpy  as np 
from sklearn.preprocessing import Binarizer, KBinsDiscretizer, FunctionTransformer

df = pd.DataFrame({
    'A':[1,2,3,4,5],
    'B':[6,2,7,9,0],
    'C':[11,55,67,5,4]
})
print(df)

print("Values \n")
print(df.values)

print("Rounding \n")
print(df.round(1))



   A  B   C
0  1  6  11
1  2  2  55
2  3  7  67
3  4  9   5
4  5  0   4
Values 

[[ 1  6 11]
 [ 2  2 55]
 [ 3  7 67]
 [ 4  9  5]
 [ 5  0  4]]
Rounding 

   A  B   C
0  1  6  11
1  2  2  55
2  3  7  67
3  4  9   5
4  5  0   4
